import Vue from "vue";
import BaseDatatable from "../components/base/BaseDatatable";
import BaseDialog from "../components/base/BaseDialog";
import BaseTextfield from "../components/base/BaseTextfield";
import BaseAcceptButton from "../components/base/BaseAcceptButton";
import BaseCancelButton from "../components/base/BaseCancelButton";
import BaseConfirmDelete from "../components/base/BaseConfirmDelete";
import BaseDatatableRowButton from "../components/base/BaseDatatableRowButton";
import BaseSnackbar from "../components/base/BaseSnackbar";
import BaseAutocomplete from "../components/base/BaseAutocomplete";
import BaseHeaderModule from "../components/base/BaseHeaderModule";
import BasePagination from "../components/base/BasePagination";
import BaseSwitch from "../components/base/BaseSwitch";
import BaseSelect from "../components/base/BaseSelect";
import { VList } from "vuetify/lib";

Vue.component("BaseDatatable", BaseDatatable);
Vue.component("BaseDialog", BaseDialog);
Vue.component("BaseTextfield", BaseTextfield);
Vue.component("BaseAcceptButton", BaseAcceptButton);
Vue.component("BaseCancelButton", BaseCancelButton);
Vue.component("BaseConfirmDelete", BaseConfirmDelete);
Vue.component("BaseSnackbar", BaseSnackbar);
Vue.component("BaseDatatableRowButton", BaseDatatableRowButton);
Vue.component("BaseAutocomplete", BaseAutocomplete);
Vue.component("BaseHeaderModule", BaseHeaderModule);
Vue.component("BasePagination", BasePagination);
Vue.component("BaseSwitch", BaseSwitch);
Vue.component("BaseSelect", BaseSelect);
Vue.component("VList", VList);
